#!/bin/sh -e

DIST_DIR=dist
SRC_DIR=src

name=$DIST_DIR/$1

mkdir -p "$DIST_DIR"
npx postcss "$SRC_DIR/$1/**/*.scss" \
	--base "$SRC_DIR" \
	--dir "$DIST_DIR" \
	--ext css
find "$name" -type f -exec cat {} \; > "$name.css"
rm -rf "$name"
