#!/bin/sh -e

DIST_DIR=dist
SRC_DIR=src

name=$DIST_DIR/${1:?}

build_fx() {
	npx postcss "$SRC_DIR/firefox/index_$1.scss" \
		--output "$DIST_DIR/firefox_$1.css"
	printf 'Built %s\n' "$1" >&2
}

mkdir -p "$DIST_DIR"
# TODO: special behavior for now
# refactor later, although steam WILL require the latter variant...
if [ "$1" = firefox ]; then
	for i in ${2:-agent author global}; do
		build_fx "$i"
	done
	exit
fi

npx postcss "$SRC_DIR/$1/**/*.scss" \
	--base "$SRC_DIR" \
	--dir "$DIST_DIR" \
	--ext css
:> "$name.css"
while IFS= read -r file; do
	# TODO(port): for now
	if [ "${file##*.}" != css ]; then
		continue
	fi

	cat "$file" >> "$name.css"
	printf '\n' >> "$name.css"
done <<-EOF
$(find "$name/" -type f)
EOF
rm -rf "$name"
